### ISSUE TITLE
Characteristics section should have role included

### ISSUE THREAD

**Issue by clapierre** [w3c/dpub-aria#36]
When reviewing this the primary role is listed first, then you have examples, and afterwards you get the characteristics, but the characteristics doesn't include the primary role i.e. doc-chapter.

Either move the characteristics above the example section or include the primary role in each of the characteristic sections.

i.e.

Characteristic | Value
-- | --
_role_ | _doc-chapter_
superclass role | landmark
related concepts | EPUB chapter [EPUB-SSV]
...

**Comment by mattgarrish** [comment]
@clapierre the current table definitions are adapted from the ARIA core specification, so I'm hesitant to make changes that would make these tables differ. I see benefit in more context, as sometimes you end up at the table and have to scroll back up to find out what section you're in, but I'd recommend opening this issue in the aria tracker.

The name of the role isn't really a characteristic of the role itself, so maybe there is some other approach like having the role name in the caption for better context (e.g., "Characteristics of doc-toc" rather than just "Characteristics").

**Comment by mattgarrish** [comment]
I've added the role names to the captions, so closing this issue. If you want them as a table row, please open an issue in the aria tracker.
